
def par(num):

    params = {
        'tn': 'resultjson_com',
        'logid': '7740562212419440587',
        'ipn': 'rj',
        'ct': '201326592',
        'is': '',
        'fp': 'result',
        'fr': '',
        'word': '孙允珠',
        'queryWord': '孙允珠',
        'cl': '2',
        'lm': '-1',
        'ie': 'utf-8',
        'oe': ' utf-8',
        'adpicid': '',
        'st': '-1',
        'z': '',
        'ic': '0',
        'hd': '',
        'latest': '',
        'copyright': '',
        's': '',
        'se': '',
        'tab': '',
        'width': '',
        'height': '',
        'face': '0',
        'istype': '2',
        'qc': '',
        'nc': '1',
        'expermode': '',
        'nojc': '',
        'isAsync': '',
        'pn': f'{num}',
        'rn': '60',
        'gsm': '1a4',
        '1649473273467': '',
    }
    return params